# Generated by Django 5.2.7 on 2025-12-22 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_agency_subscription'),
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencypayment',
            name='currency',
            field=models.CharField(default='SAR', max_length=3),
        ),
        migrations.AddField(
            model_name='agencypayment',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='agencypayment',
            name='moyasar_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='agencypayment',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agencypayment',
            name='raw',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agencypayment',
            name='transaction_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agencypayment',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.agency'),
        ),
        migrations.AlterField(
            model_name='agencypayment',
            name='amount',
            field=models.IntegerField(help_text='Amount in halalas'),
        ),
        migrations.AlterField(
            model_name='agencypayment',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('paid', 'Paid'), ('failed', 'Failed')], default='initiated', max_length=20),
        ),
    ]
